# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "associations", :force => true do |t|
    t.binary   "server_url"
    t.binary   "secret"
    t.string   "handle"
    t.string   "assoc_type"
    t.integer  "issued"
    t.integer  "lifetime"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "authentifications", :force => true do |t|
    t.string   "email",      :default => "", :null => false
    t.string   "ok_hash",    :default => "", :null => false
    t.text     "auth_data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "nonces", :force => true do |t|
    t.string   "nonce"
    t.integer  "created"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "settings", :force => true do |t|
    t.string   "setting"
    t.binary   "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "trusts", :force => true do |t|
    t.integer  "user_id"
    t.string   "trust_root"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
